package cinepeliculeon;

/**
 *
 * @author LENNY
 */
public class menuAdmin extends javax.swing.JFrame {


    /**
     * Creates new form Prueba2
     */
    public menuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        buttonRegistrarPeli = new javax.swing.JButton();
        buttonRegistrarSucur = new javax.swing.JButton();
        buttonEstablecerSalas = new javax.swing.JButton();
        buttonAgregarPeli = new javax.swing.JButton();
        buttonAsignarHoararios = new javax.swing.JButton();
        buttonRegistrarEmpleado = new javax.swing.JButton();
        buttonReportes = new javax.swing.JButton();
        buttonCerrarSesionAd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(94, 17, 47));
        Menu.setPreferredSize(new java.awt.Dimension(354, 600));

        buttonRegistrarPeli.setBackground(new java.awt.Color(253, 185, 19));
        buttonRegistrarPeli.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        buttonRegistrarPeli.setText("REGISTRAR PELICULA");
        buttonRegistrarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarPeliActionPerformed(evt);
            }
        });

        buttonRegistrarSucur.setBackground(new java.awt.Color(253, 185, 19));
        buttonRegistrarSucur.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        buttonRegistrarSucur.setText("REGISTRAR SUCURSAL");
        buttonRegistrarSucur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarSucurActionPerformed(evt);
            }
        });

        buttonEstablecerSalas.setBackground(new java.awt.Color(253, 185, 19));
        buttonEstablecerSalas.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        buttonEstablecerSalas.setText("ESTABLECER SALAS");
        buttonEstablecerSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEstablecerSalasActionPerformed(evt);
            }
        });

        buttonAgregarPeli.setBackground(new java.awt.Color(253, 185, 19));
        buttonAgregarPeli.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        buttonAgregarPeli.setText("AGREGAR PELICULA");
        buttonAgregarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarPeliActionPerformed(evt);
            }
        });

        buttonAsignarHoararios.setBackground(new java.awt.Color(253, 185, 19));
        buttonAsignarHoararios.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        buttonAsignarHoararios.setText("ASIGNAR HORARIOS");
        buttonAsignarHoararios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAsignarHoarariosActionPerformed(evt);
            }
        });

        buttonRegistrarEmpleado.setBackground(new java.awt.Color(253, 185, 19));
        buttonRegistrarEmpleado.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        buttonRegistrarEmpleado.setText("REGISTRO DE EMPLEADOS");
        buttonRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarEmpleadoActionPerformed(evt);
            }
        });

        buttonReportes.setBackground(new java.awt.Color(253, 185, 19));
        buttonReportes.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        buttonReportes.setText("REPORTES");
        buttonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReportesActionPerformed(evt);
            }
        });

        buttonCerrarSesionAd.setBackground(new java.awt.Color(253, 185, 19));
        buttonCerrarSesionAd.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        buttonCerrarSesionAd.setText("CERRAR SESION");
        buttonCerrarSesionAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarSesionAdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRegistrarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRegistrarSucur, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonEstablecerSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAgregarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAsignarHoararios, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCerrarSesionAd, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(buttonRegistrarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRegistrarSucur, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEstablecerSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAgregarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAsignarHoararios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCerrarSesionAd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 354, 600));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMINISTRADOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 360, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Letter - 45.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegistrarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarPeliActionPerformed

        panelRegistrarPelicula panelPelicula = new panelRegistrarPelicula();
        panelPelicula.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonRegistrarPeliActionPerformed

    private void buttonRegistrarSucurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarSucurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegistrarSucurActionPerformed

    private void buttonEstablecerSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEstablecerSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEstablecerSalasActionPerformed

    private void buttonAgregarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarPeliActionPerformed

        selecSucursal selecPeli = new selecSucursal();
        selecPeli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonAgregarPeliActionPerformed

    private void buttonAsignarHoarariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAsignarHoarariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAsignarHoarariosActionPerformed

    private void buttonRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegistrarEmpleadoActionPerformed

    private void buttonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReportesActionPerformed

    private void buttonCerrarSesionAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarSesionAdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCerrarSesionAdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JButton buttonAgregarPeli;
    private javax.swing.JButton buttonAsignarHoararios;
    private javax.swing.JButton buttonCerrarSesionAd;
    private javax.swing.JButton buttonEstablecerSalas;
    private javax.swing.JButton buttonRegistrarEmpleado;
    private javax.swing.JButton buttonRegistrarPeli;
    private javax.swing.JButton buttonRegistrarSucur;
    private javax.swing.JButton buttonReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
//OJITO