/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinepeliculeon;

import db.Mysql;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author LENNY
 */
public class panelRegistrarPelicula extends javax.swing.JFrame {
    /**
     * Creates new form PanelRegistrarPelicula
     */
    public panelRegistrarPelicula() {
        initComponents();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelRegistrarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelRegistrarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelRegistrarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelRegistrarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        n1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtduracion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtsipnopsis = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboGenero = new javax.swing.JComboBox<>();
        botonGuardarRegistroPelicula = new javax.swing.JButton();
        botonCancelarRegistrodePeli = new javax.swing.JButton();
        botonAgregarImagen = new javax.swing.JButton();
        labelAgregarImagen = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REGISTRAR PELICULA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 430, 50));

        n1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        n1.setForeground(new java.awt.Color(255, 255, 255));
        n1.setText("NOMBRE: ");
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 200, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DURACION:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        txtduracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtduracionActionPerformed(evt);
            }
        });
        getContentPane().add(txtduracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 200, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SIPNOPSIS:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, 20));

        txtsipnopsis.setColumns(20);
        txtsipnopsis.setRows(5);
        jScrollPane1.setViewportView(txtsipnopsis);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CATEGORIA:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 200, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("GENERO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Comedia", "Drama", "Terror", "Ciencia Ficción" }));
        getContentPane().add(comboGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 200, -1));

        botonGuardarRegistroPelicula.setBackground(new java.awt.Color(230, 12, 16));
        botonGuardarRegistroPelicula.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        botonGuardarRegistroPelicula.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarRegistroPelicula.setText("Guardar ");
        botonGuardarRegistroPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarRegistroPeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardarRegistroPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 320, 47));

        botonCancelarRegistrodePeli.setBackground(new java.awt.Color(230, 12, 16));
        botonCancelarRegistrodePeli.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        botonCancelarRegistrodePeli.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelarRegistrodePeli.setText("Cancelar");
        botonCancelarRegistrodePeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarRegistrodePeliActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelarRegistrodePeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 320, 47));

        botonAgregarImagen.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        botonAgregarImagen.setText("AGREGAR IMAGEN");
        botonAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarImagenActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));
        getContentPane().add(labelAgregarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 200, 200));

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/labelImagenPelicula.png"))); // NOI18N
        getContentPane().add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 200, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        String nombre = txtnombre.getText();
        if (nombre.length() > 30) {
            txtnombre.setText(nombre.substring(0, 30));
        }
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtduracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtduracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtduracionActionPerformed

    public String imagenSeleccionada;
    
    private void botonAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarImagenActionPerformed
    JFileChooser jf = new JFileChooser();
    jf.setFileFilter(new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png", "gif"));
    
    int result = jf.showOpenDialog(this);
    
    if (result == JFileChooser.APPROVE_OPTION) {
        File file = jf.getSelectedFile();
        String filePath = file.getAbsolutePath();
        
        String nombrePelicula = txtnombre.getText().trim();
        if (nombrePelicula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "❌ El nombre de la película no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String nuevaRuta = "src/imagenes/" + nombrePelicula + "." + obtenerExtension(filePath);
        
        File destino = new File(nuevaRuta);
        try {
            Files.copy(file.toPath(), destino.toPath(), StandardCopyOption.REPLACE_EXISTING);
            imagenSeleccionada = nuevaRuta;
            JOptionPane.showMessageDialog(this, "✅ Imagen copiada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            ImageIcon imageIcon = new ImageIcon(nuevaRuta);
            Image image = imageIcon.getImage().getScaledInstance(labelAgregarImagen.getWidth(), labelAgregarImagen.getHeight(), Image.SCALE_SMOOTH);
            labelAgregarImagen.setIcon(new ImageIcon(image));

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "❌ Error al copiar la imagen: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_botonAgregarImagenActionPerformed

    private String obtenerExtension(String filePath) {
        String extension = "";
        int i = filePath.lastIndexOf('.');
        if (i > 0) {
            extension = filePath.substring(i + 1);
        }
        return extension;
    }

    private void botonGuardarRegistroPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarRegistroPeliculaActionPerformed

        String nombrePeli = txtnombre.getText();
        int duracion = 0;

        try {
            duracion = Integer.parseInt(txtduracion.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "❌ La duración debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String sipnopsis = txtsipnopsis.getText();
        String genero = comboGenero.getSelectedItem().toString();
        String categoria = comboCategoria.getSelectedItem().toString();

        Mysql db = new Mysql();
        int resultado = db.registrarPelicula(nombrePeli, duracion, sipnopsis, genero, categoria,imagenSeleccionada);

        if (resultado > 0) {
            JOptionPane.showMessageDialog(this, "✅ Película registrada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "❌ Error al registrar la película.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_botonGuardarRegistroPeliculaActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed

    }//GEN-LAST:event_comboCategoriaActionPerformed

    private void botonCancelarRegistrodePeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarRegistrodePeliActionPerformed
        menuAdmin adminMenu = new menuAdmin();
        adminMenu.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_botonCancelarRegistrodePeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelRegistrarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelRegistrarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelRegistrarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelRegistrarPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelRegistrarPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarImagen;
    private javax.swing.JButton botonCancelarRegistrodePeli;
    private javax.swing.JButton botonGuardarRegistroPelicula;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAgregarImagen;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel n1;
    private javax.swing.JTextField txtduracion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextArea txtsipnopsis;
    // End of variables declaration//GEN-END:variables
}
