/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package cinepeliculeon;

/**
 *
 * @author LENNY
 */
public class selecSucursal extends javax.swing.JFrame {

    private String sucursalSeleccionada;
    
    public selecSucursal() {
        initComponents();
        agregarEventos();
    }

    private void agregarEventos() {
        botonSelecCercado.addActionListener(e -> abrirListaPeliculas("CERCADO", 3));
        botonSelecQuillacollo.addActionListener(e -> abrirListaPeliculas("QUILLACOLLO", 2));
        botonSelecSacaba.addActionListener(e -> abrirListaPeliculas("SACABA", 1));
    }

    private void abrirListaPeliculas(String nombreSucursal, int idSucursal) {
        // Guardamos la sucursal seleccionada
        listaPeliculas frame;
        switch (idSucursal) {
            case 3:
                frame = new listaPeliculasCercado(nombreSucursal, idSucursal);
                break;
            case 2:
                frame = new listaPeliculasQuillacollo(nombreSucursal, idSucursal);
                break;
            case 1:
                frame = new listaPeliculasSacaba(nombreSucursal, idSucursal);
                break;
            default:
                return;
        }

        frame.setVisible(true);
        this.dispose();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonSelecCercado = new javax.swing.JButton();
        botonSelecQuillacollo = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botonSelecSacaba = new javax.swing.JButton();
        fondoSelecSucursal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECCIONA SUCURSAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 43, -1, -1));

        botonSelecCercado.setBackground(new java.awt.Color(22, 184, 242));
        botonSelecCercado.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonSelecCercado.setForeground(new java.awt.Color(255, 255, 255));
        botonSelecCercado.setText("Cercado");
        botonSelecCercado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(botonSelecCercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 155, 370, 75));

        botonSelecQuillacollo.setBackground(new java.awt.Color(22, 184, 242));
        botonSelecQuillacollo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonSelecQuillacollo.setForeground(new java.awt.Color(255, 255, 255));
        botonSelecQuillacollo.setText("Quillacollo");
        getContentPane().add(botonSelecQuillacollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 292, 370, 75));

        botonAtras.setBackground(new java.awt.Color(230, 12, 16));
        botonAtras.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        botonAtras.setForeground(new java.awt.Color(255, 255, 255));
        botonAtras.setText("Atrás");
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 528, 320, 47));

        botonSelecSacaba.setBackground(new java.awt.Color(22, 184, 242));
        botonSelecSacaba.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        botonSelecSacaba.setForeground(new java.awt.Color(255, 255, 255));
        botonSelecSacaba.setText("Sacaba");
        botonSelecSacaba.setActionCommand("");
        getContentPane().add(botonSelecSacaba, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 429, 370, 75));

        fondoSelecSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Letter - 47.png"))); // NOI18N
        fondoSelecSucursal.setText("jLabel1");
        fondoSelecSucursal.setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().add(fondoSelecSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selecSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selecSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selecSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selecSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selecSucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonSelecCercado;
    private javax.swing.JButton botonSelecQuillacollo;
    private javax.swing.JButton botonSelecSacaba;
    private javax.swing.JLabel fondoSelecSucursal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
