/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import baseDatos.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class InicioSesion extends javax.swing.JFrame {

    
    private Connection conexion;
    
    public InicioSesion() {
        initComponents();
        setResizable(false);
        setTitle("Inicio de Sesión");
        setLocationRelativeTo(null);
        
        try {
            conexion = ConexionBD.getConnection();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error al conectar con la base de datos: " + e.getMessage(),
                "Error de Conexión",
                JOptionPane.ERROR_MESSAGE);
        }
        
        // Agregar el ActionListener al botón
        btn_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciar_sesionActionPerformed(evt);
            }
        });
    }
    
    private boolean esCorreoValido(String correo) {
        String regex = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        return pattern.matcher(correo).matches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_correo = new javax.swing.JTextField();
        jLaInicioSesion = new javax.swing.JLabel();
        btn_iniciar_sesion = new javax.swing.JButton();
        contra = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(39, 29, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_correo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_correo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_correoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 320, 50));

        jLaInicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 58)); // NOI18N
        jLaInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        jLaInicioSesion.setText("INICIO SESION");
        jPanel1.add(jLaInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 430, 58));

        btn_iniciar_sesion.setBackground(new java.awt.Color(255, 0, 0));
        btn_iniciar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_iniciar_sesion.setForeground(new java.awt.Color(255, 255, 255));
        btn_iniciar_sesion.setText("INICIAR SESION");
        btn_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciar_sesionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 320, 47));

        contra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        contra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 320, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 1250, 740));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_correoActionPerformed

    private void btn_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciar_sesionActionPerformed
    String correo = txt_correo.getText().trim();
        String password = new String(contra.getPassword());
        
        // Validar que los campos no estén vacíos
        if (correo.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor complete todos los campos",
                "Campos Vacíos",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validar formato de correo
        if (!esCorreoValido(correo)) {
            JOptionPane.showMessageDialog(this,
                "Por favor ingrese un correo válido",
                "Correo Inválido",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Consulta SQL para verificar las credenciales
        String sql = "SELECT ID_EMPLE, CARGO_USUARIO FROM usuario " +
                    "WHERE Correo_USUARIO = ? AND Contra_USUARIO = ?";
        
        try (PreparedStatement stmt = conexion.prepareStatement(sql)) {
            stmt.setString(1, correo);
            stmt.setString(2, password);
            
            ResultSet rs = stmt.executeQuery();
            
            if (rs.next()) {
                int cargoUsuario = rs.getInt("CARGO_USUARIO");
                int idEmpleado = rs.getInt("ID_EMPLE");
                
                InicioSesion.SesionUsuario.setIdEmpleado(idEmpleado);
                
                // Cerrar la ventana de login
                this.dispose();
                
                // Abrir el menú correspondiente según el cargo
                if (cargoUsuario == 0) {
                    // Es administrador
                    java.awt.EventQueue.invokeLater(() -> {
                        MenuAdminBar menuAdmin = new MenuAdminBar();
                        menuAdmin.setVisible(true);
                    });
                } else if (cargoUsuario == 1) {
                    // Es empleado
                    java.awt.EventQueue.invokeLater(() -> {
                        MenuEmpleado menuEmpleado = new MenuEmpleado();
                        menuEmpleado.setVisible(true);
                    });
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "Correo o contraseña incorrectos",
                    "Error de Autenticación",
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error al intentar iniciar sesión: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_iniciar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }
    public static class SesionUsuario {
        private static int idEmpleadoActual;
        
        public static void setIdEmpleado(int id) {
            idEmpleadoActual = id;
        }
        
        public static int getIdEmpleado() {
            return idEmpleadoActual;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar_sesion;
    private javax.swing.JPasswordField contra;
    private javax.swing.JLabel jLaInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_correo;
    // End of variables declaration//GEN-END:variables
}
