/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Tommy
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        setResizable(false);
        setTitle("Inicio de Sesión");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTexCorreoElectronico = new javax.swing.JTextField();
        jLaInicioSesion = new javax.swing.JLabel();
        jRAdministrador = new javax.swing.JRadioButton();
        jREmpleado = new javax.swing.JRadioButton();
        jButIniciarSesion = new javax.swing.JButton();
        jTexContrasenia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(39, 29, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTexCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTexCorreoElectronico.setText("correo electronico");
        jTexCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexCorreoElectronicoActionPerformed(evt);
            }
        });
        jPanel1.add(jTexCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 320, 47));

        jLaInicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 58)); // NOI18N
        jLaInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        jLaInicioSesion.setText("INICIO SESION");
        jPanel1.add(jLaInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 430, 58));

        jRAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jRAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        jRAdministrador.setText("ADMINISTRADOR");
        jPanel1.add(jRAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 250, 48));

        jREmpleado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jREmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jREmpleado.setText("EMPLEADO");
        jREmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jREmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(jREmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 230, 48));

        jButIniciarSesion.setBackground(new java.awt.Color(255, 0, 0));
        jButIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jButIniciarSesion.setText("INICIAR SESION");
        jButIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(jButIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 320, 47));

        jTexContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTexContrasenia.setText("contraseña");
        jTexContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexContraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(jTexContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 320, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGOCENTRO.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 33, 1096, 687));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTexCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexCorreoElectronicoActionPerformed

    private void jButIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButIniciarSesionActionPerformed

    private void jTexContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexContraseniaActionPerformed

    private void jREmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jREmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jREmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButIniciarSesion;
    private javax.swing.JLabel jLaInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRAdministrador;
    private javax.swing.JRadioButton jREmpleado;
    private javax.swing.JTextField jTexContrasenia;
    private javax.swing.JTextField jTexCorreoElectronico;
    // End of variables declaration//GEN-END:variables
}
