/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Tommy
 */
public class SucursalPelicula extends javax.swing.JFrame {

    /**
     * Creates new form SucursalPelicula
     */
    public SucursalPelicula() {
        initComponents();
        setResizable(false);
        setTitle("Sucursal Pelicula");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_cercado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_sacaba = new javax.swing.JButton();
        btn_quillacollo = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(39, 29, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cercado.setBackground(new java.awt.Color(0, 204, 255));
        btn_cercado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_cercado.setForeground(new java.awt.Color(255, 255, 255));
        btn_cercado.setText("CERCADO");
        btn_cercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cercadoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 290, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECCIONAR SUCURSAL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        btn_sacaba.setBackground(new java.awt.Color(0, 204, 255));
        btn_sacaba.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_sacaba.setForeground(new java.awt.Color(255, 255, 255));
        btn_sacaba.setText("SACABA");
        btn_sacaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sacabaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sacaba, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 290, 70));

        btn_quillacollo.setBackground(new java.awt.Color(0, 204, 255));
        btn_quillacollo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_quillacollo.setForeground(new java.awt.Color(255, 255, 255));
        btn_quillacollo.setText("QUILLACOLLO");
        btn_quillacollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quillacolloActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quillacollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 290, 80));

        btn_atras.setBackground(new java.awt.Color(255, 0, 0));
        btn_atras.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_atras.setForeground(new java.awt.Color(255, 255, 255));
        btn_atras.setText("Atras");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, 370, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGOCENTRO.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 1020, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cercadoActionPerformed
    new ListaDePeliculas("Cercado").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cercadoActionPerformed

    private void btn_sacabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sacabaActionPerformed
    new ListaDePeliculas("Sacaba").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sacabaActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
    MenuAdmin adminMenu = new MenuAdmin();
    adminMenu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_quillacolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quillacolloActionPerformed
     new ListaDePeliculas("Quillacollo").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_quillacolloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SucursalPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SucursalPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SucursalPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SucursalPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SucursalPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_cercado;
    private javax.swing.JButton btn_quillacollo;
    private javax.swing.JButton btn_sacaba;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
