/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaceSucursal;

/**
 *
 * @author Camilo PC
 */
public class salasSucursal extends javax.swing.JFrame {

    /**
     * Creates new form salasSucursal
     */
    public salasSucursal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.*/
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sala3_hab = new javax.swing.JRadioButton();
        sala1_hab = new javax.swing.JRadioButton();
        sala1_des = new javax.swing.JRadioButton();
        sala2_hab = new javax.swing.JRadioButton();
        sala2_des = new javax.swing.JRadioButton();
        sala3_des = new javax.swing.JRadioButton();
        sala5_hab = new javax.swing.JRadioButton();
        sala5_des = new javax.swing.JRadioButton();
        sala4_hab = new javax.swing.JRadioButton();
        sala4_des = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(39, 29, 41));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(22, 184, 242));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SALA 2");
        jLabel3.setMaximumSize(new java.awt.Dimension(36, 16));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 228, 53));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALAS - SUCURSAL CERCADO");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(22, 184, 242));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SALA 1");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 142, 228, 53));

        jLabel4.setBackground(new java.awt.Color(22, 184, 242));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SALA 5");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 323, 228, 53));

        jLabel5.setBackground(new java.awt.Color(22, 184, 242));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SALA 3");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 142, 228, 53));

        jLabel6.setBackground(new java.awt.Color(22, 184, 242));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SALA 4");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 323, 228, 53));

        jButton1.setBackground(new java.awt.Color(230, 12, 16));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 507, 320, 47));

        jButton2.setBackground(new java.awt.Color(230, 12, 16));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Guardar Cambios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 507, 320, 47));

        sala3_hab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sala3_hab.setForeground(new java.awt.Color(255, 255, 255));
        sala3_hab.setText("Habilitado");
        sala3_hab.setToolTipText("");
        sala3_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala3_habActionPerformed(evt);
            }
        });
        jPanel1.add(sala3_hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 209, -1, -1));

        sala1_hab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sala1_hab.setForeground(new java.awt.Color(255, 255, 255));
        sala1_hab.setText("Habilitado");
        sala1_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala1_habActionPerformed(evt);
            }
        });
        jPanel1.add(sala1_hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 212, -1, -1));

        sala1_des.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sala1_des.setForeground(new java.awt.Color(255, 255, 255));
        sala1_des.setText("Deshabilitado");
        jPanel1.add(sala1_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 255, -1, -1));

        sala2_hab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sala2_hab.setForeground(new java.awt.Color(255, 255, 255));
        sala2_hab.setText("Habilitado");
        sala2_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala2_habActionPerformed(evt);
            }
        });
        jPanel1.add(sala2_hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 212, -1, -1));

        sala2_des.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sala2_des.setForeground(new java.awt.Color(255, 255, 255));
        sala2_des.setText("Deshabilitado");
        sala2_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala2_desActionPerformed(evt);
            }
        });
        jPanel1.add(sala2_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 255, -1, -1));

        sala3_des.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sala3_des.setForeground(new java.awt.Color(255, 255, 255));
        sala3_des.setText("Deshabilitado");
        jPanel1.add(sala3_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 252, -1, -1));

        sala5_hab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sala5_hab.setForeground(new java.awt.Color(255, 255, 255));
        sala5_hab.setText("Habilitado");
        sala5_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala5_habActionPerformed(evt);
            }
        });
        jPanel1.add(sala5_hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        sala5_des.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sala5_des.setForeground(new java.awt.Color(255, 255, 255));
        sala5_des.setText("Deshabilitado");
        jPanel1.add(sala5_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        sala4_hab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sala4_hab.setForeground(new java.awt.Color(255, 255, 255));
        sala4_hab.setText("Habilitado");
        sala4_hab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala4_habActionPerformed(evt);
            }
        });
        jPanel1.add(sala4_hab, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        sala4_des.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sala4_des.setForeground(new java.awt.Color(255, 255, 255));
        sala4_des.setText("Deshabilitado");
        sala4_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sala4_desActionPerformed(evt);
            }
        });
        jPanel1.add(sala4_des, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sala1_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala1_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sala1_habActionPerformed

    private void sala2_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala2_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sala2_desActionPerformed

    private void sala4_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala4_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sala4_habActionPerformed

    private void sala5_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala5_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sala5_habActionPerformed

    private void sala2_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala2_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sala2_habActionPerformed

    private void sala3_habActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala3_habActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sala3_habActionPerformed

    private void sala4_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sala4_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sala4_desActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salasSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salasSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salasSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salasSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salasSucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton sala1_des;
    private javax.swing.JRadioButton sala1_hab;
    private javax.swing.JRadioButton sala2_des;
    private javax.swing.JRadioButton sala2_hab;
    private javax.swing.JRadioButton sala3_des;
    private javax.swing.JRadioButton sala3_hab;
    private javax.swing.JRadioButton sala4_des;
    private javax.swing.JRadioButton sala4_hab;
    private javax.swing.JRadioButton sala5_des;
    private javax.swing.JRadioButton sala5_hab;
    // End of variables declaration//GEN-END:variables
}
